### ISSUE TITLE
A few minor issues

### ISSUE THREAD

**Issue by yarusome** [Vallek/animatable-css#1]
1. `index.js` seems not included in the GitHub Page.
2. For the animation type of `z-index`, the first paragraph in [Appendix A](https://drafts.csswg.org/web-animations-1/#animation-types) of Web Animations implies that it should be "by computed value", thus MDN is incorrect here. ~(Although for integer-valued properties, "by computed value" and "discrete" exhibit the same behavior.)~

Kudos to your job so far :+1: You may also visit the somewhat related my [diff-webref-mdn](https://github.com/yarusome/diff-webref-mdn) repo.

**Comment by Vallek** [comment]
@yarusome Thanks for feedback! The last commit broke the build btw so properties weren't loaded, it's fixed now. upd (aaaand happened again)

1. Yes this is by design. index.html is build from index.js on node.js by github actions and then put in gh-pages.
2. Oh that's interesting. So should everything from [Other cases](https://vallek.github.io/animatable-css/#other) have "by computed value"? Cause it's not in api right?
3. I was looking for mdn api but didn't found it. So there is one) Well seems like they deprecating it https://github.com/mdn/data/#welcome-to-mdn-data in favor of [w3c/webref](https://github.com/w3c/webref)

**Comment by yarusome** [comment]
1. OK, when I visited the page, the two sections were blank, but not anymore now :)
2. Yes.
3. The deprecation seems stalled. I do see its value since most developers cannot easily tell which level of each spec has actually been widely implemented.

**Comment by Vallek** [comment]
@yarusome 
2. Ok, well since animation not applied to voice (i'm guessing) I think I can remove that spec entirely and put everything else with "by computed value".

PS I don't think you should close issues yourself in others repos) There still might be something to discuss. More importantly people should see if it's not fixed yet.

**Comment by yarusome** [comment]
The main issue was Point 1, but fair enough, I'm reopening the issue.

---

Actually, the presence of both Level 3 and Level 4 of CSS Backgrounds and Borders Module on the page underscores [Point 3](https://github.com/Vallek/animatable-css/issues/1#issuecomment-1607323323).

Another minor issue I found with the current layout is that some specs have so many properties that a single column becomes really lengthy. Instead of using `break-inside: avoid`, and for better use of the space while keeping the multi-column layout, it could be done that:

1. Remove the `lists` class;

2. Use something like below:

   ```css
   @media screen and (min-width: 800px) {
     section > ul {
       display: flex;
       flex-wrap: wrap;
     }
     section > ul > li {
       margin-right: 3%;
       width: 30%;
     }
   }
   ```

   or even more gradual transition:

   ```css
   @media screen and (min-width: 500px) {
     section > ul {
       display: flex;
       flex-wrap: wrap;
     }
     section > ul > li {
       margin-right: 5%;
       width: 45%;
     }
   }
   @media screen and (min-width: 800px) {
     section > ul > li {
       margin-right: 3%;
       width: 30%;
     }
   }
   ```
